# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "앱을 빌드 후 Testflight에 업로드합니다"

  lane :beta do
    

    # 아래 명령에 오류가 있어 주석처리 
    # get_certificates
    # get_provisioning_profile
    
    # 최신 빌드 번호 받아오기 (App Store Connect에서)
    latest_build_number = latest_testflight_build_number(
      app_identifier: "run.ddd.MOZIP"
    )
    
    new_build_number = latest_build_number + 1

    project_file_path = "../Targets/Mozip/Project.swift"

    version_number = sh("grep 'CFBundleShortVersionString' #{project_file_path} | sed -E 's/.*\"([0-9\\.]+)\".*/\\1/'").strip

    # Project.swift 파일 내 buildNumber를 찾아서 숫자를 바꿔주는 작업. 아래 코드 형태가 바뀌면 작동 안됨.
    sh("sed -i '' 's/static let buildNumber = \".*\"/static let buildNumber = \"#{new_build_number}\"/' #{project_file_path}")

    # fastlane match 파일 추가 후 적용됨
    #sync_code_signing(
    #  type: "appstore",
    #  app_identifier: 'run.ddd.MOZIP',
    #  readonly: true
    #)
    
    # 2FA 인증방식 대신 아래방식을 사용 
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    sh("cd .. && tuist generate")

    build_app(
      scheme: "MOZIP",  
      configuration: "Release"
    )
    upload_to_testflight

    # Git 커밋 및 푸시
    commit_message = "release: v#{version_number} (#{new_build_number}) 버전 배포"
    sh("cd .. && git add .")
    sh("cd .. && git commit -m '#{commit_message}'")
    #sh("cd .. && git push")
  end
end


# 테스트
# tuist menifest 파일에서 환경변수를 사용하기 위해선, TUIST_ 접두어를 붙여주어야 가능하다..!

lane :test do
  sh("pwd")
  sh("cd .. && tuist generate")
end
