# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "앱을 빌드 후 Testflight에 업로드합니다"

  lane :beta do
    sh("cd .. && tuist generate")

    # 아래 명령에 오류가 있어 주석처리 
        # get_certificates
        # get_provisioning_profile

    build_app(
      scheme: "MOZIP",  
      configuration: "Release"
    )
    upload_to_testflight
  end
end


# 테스트
# tuist menifest 파일에서 환경변수를 사용하기 위해선, TUIST_ 접두어를 붙여주어야 가능하다..!

lane :test do
  sh("pwd")
  sh("cd .. && tuist generate")
end
