# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "앱을 빌드 후 Testflight에 업로드합니다"
  lane :beta do

    # 버전 번호 설정
    version_number = "1.2.1"

    # 빌드 번호 설정
    build_number = "1"

    # Tuist 실행 시 환경 변수 전달
    Dir.chdir("/Users/leewonbeen/Desktop/Home/DDD_Project/DDD-11-Dissonance-iOS") do
      sh("TUIST_VERSION_NUMBER=#{version_number} TUIST_BUILD_NUMBER=#{build_number} tuist generate")
    end

    get_certificates
    get_provisioning_profile

    build_app(
      scheme: "MOZIP",  
      configuration: "Debug"
    )
    upload_to_testflight
    # add actions here: https://docs.fastlane.tools/actions
  end
end


# 테스트
# tuist menifest 파일에서 환경변수를 사용하기 위해선, TUIST_ 접두어를 붙여주어야 가능하다..!

lane :test do
    # 버전 번호 설정
    version_number = "1.2.1"

    # 빌드 번호 설정
    build_number = "2"

    # Tuist 실행 시 환경 변수 전달
    Dir.chdir("/Users/leewonbeen/Desktop/Home/DDD_Project/DDD-11-Dissonance-iOS") do
      sh("TUIST_VERSION_NUMBER=#{version_number} TUIST_BUILD_NUMBER=#{build_number} tuist generate")
    end
end
